# Generated by Django 3.2 on 2021-04-27 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='msgtitle',
            field=models.CharField(default='沒有標題', max_length=25),
        ),
    ]
